### PR TITLE
204 my markets

### PR DESCRIPTION
**Pull request by stephensprinkle-zz**

### CODE REVIEW

**Comment by thinkloop** [comment]
is this waiting for review or still applying changes?

**Comment by stephensprinkle** [comment]
Just pushed the final set of changes.

**Comment by thinkloop** [comment]
Hey @stephensprinkle,

1. There's currently a 'positions' module, which displays positions both in the portfolio page and market-details page (and possibly other places). My-markets and my-reports will also be re-used on the market-details page and other places, so I think it makes sense to have them grouped together. To be consistent we should make modules for 'my-markets', and 'my-reports' while keeping 'portfolio' where they come together, or get rid of 'positions', I vote for the former.

2. Add my-markets display to market-detail page

3. I removed tables.less, it didn't have much in it, and generally the app names specific sections and elements for custom styling.

**Comment by stephensprinkle** [comment]
Updated tasks related to issue here: https://github.com/AugurProject/augur/issues/204#issuecomment-237622383

**Pull request merged**
