### PR TITLE
339 missing no

### PR DESCRIPTION
**Pull request by stephensprinkle-zz**

### CODE REVIEW

**Comment by tinybike** [comment]
One of the tests is failing:
```
  1) augur-ui-react-components market state market.outcomes:
     TypeError: Cannot read property 'forEach' of undefined
      at market.js:223:5
      at Array.forEach (native)
      at Context.<anonymous> (market.js:122:20)
```

**Comment by stephensprinkle** [comment]
Interesting…I’d originally done a std push (linting/tests) — just did another check of the tests w/ all passing locally — pushed up a rebase against master…let’s see what happens :)

**Comment by stephensprinkle** [comment]
Ah, looks to fail specifically when tested against node 6.5.0.

**Comment by stephensprinkle** [comment]
Very odd that npm run courage was failing but npm run test wasn’t — latest push should resolve.

**Comment by tinybike** [comment]
https://github.com/AugurProject/augur/pull/763 is still failing for me when I try to run it in the browser -- should I hold off on merging this until that one is ready?

**Comment by stephensprinkle** [comment]
Ok, I’m seeing the issue now — give me just a minute to resolve.

**Pull request merged**
